### ISSUE TITLE
Error failed to fetch an image or build from source

### ISSUE THREAD

**Issue by jackmcdade** [gregmsanderson/fly-hello-laravel#1]
I tried a few times to get this deployed to try out fly but each time I get stuck near the end, on the `npm install` step, with this error message:

```
Error failed to fetch an image or build from source: error building: executor failed running [/bin/sh -c npm install && npm run prod]: exit code: 243
```

**Comment by gregmsanderson** [comment]
Strange ...  Sounds like it's _this_ line in the Dockerfile it's not happy with:

https://github.com/gregmsanderson/fly-hello-laravel/blob/main/Dockerfile#L96

That runs the _prod_ command, which in turn just runs mix for css/js:

https://github.com/gregmsanderson/fly-hello-laravel/blob/main/package.json#L9

Does your Laravel app use mix? Or are you trying to deploy this sample app? If you don't use mix and so don't need to run `npm run prod` at all, you could just delete that entire line from your copy of the Dockerfile. Since the only reason to run `npm install` at all is _for_ mix. I mean it _should_ still work with it, but it would be interesting for debugging to see what happens for you without that line.

**Comment by jackmcdade** [comment]
I tried it on my own app which uses mix, and a simple clone of this app without changing anything but the app name and generating a new key and had the same issue both times. 

Commenting out the line 96 of the Dockerfile did fix it. Any idea what's up with node in this build?

**Comment by gregmsanderson** [comment]
It's good to hear it is working. You make a good point ... what _has_ changed since then? Hmm ... not sure!

I guess to pursue debugging this it would be a case of splitting that line in two: run `npm install` as its own line in the Dockerfile, and then `npm run prod` underneath. And since which of those two throws the error. And then proceed from there. It may be a general node/npm issue _or_ caused by mix. I'll try my own deploy at some point since it _did_ work.

**Comment by jackmcdade** [comment]
I just split it up and it fails on the `npm run production` step.

**Comment by gregmsanderson** [comment]
Ah, that's some progress. So node and npm are fine, it's mix.

I don't actually know why Laravel chose to add separate "prod" _and_ "production". I mean it saves a few characters I guess, but still! It's their default package.json file: https://laravel.com/docs/9.x/mix#running-mix

So that in turn runs `mix --production`. So _that's_ failing. Hmm. I wonder if it needs to be `npx mix`, or have the full path? Not simply be `mix`. Could that be it? :thinking:

**Comment by jackmcdade** [comment]
Ahh no way, `RUN npx mix` worked. I've never had to do that locally before, but then again I don't use Docker. Maybe there's an issue with the way the cli aliases the `mix` command? Oddly, the production flag didn't work: `RUN npx mix --production`.

**Comment by gregmsanderson** [comment]
Interesting! I'm guessing so.

Likewise, locally I can run `mix`. Which is why e.g `npm run prod` would _also_ work. `npx` is going to check the PATH, I guess find `mix` is not there and _presumably_ run the local `bin` (the one in `node_modules`). Which would explain why that works. Not sure why it's not happy with the flag though.

Seems there may be some quirk after a quick search e.g this unanswered question. Not the same problem, but it may relate to how npx processes flags. https://stackoverflow.com/questions/72046058/npx-mix-watch-giving-different-results-to-npx-mix-production

**Comment by gregmsanderson** [comment]
Updated `Dockerfile` to use npx. And while there, also removed the `--no-cache` flag from the `apk` installs. As randomly that flag would cause those installs to fail e.g `nginx`.

Just tried a deploy myself with those changes and it works :)

**Comment by jackmcdade** [comment]
`npx` works, but I still have issues with `npx —production`. You?

**Comment by gregmsanderson** [comment]
Weird. Worked fine for me.

In the `Dockerfile` I moved it into a separate line to debug:

```
# Laravel's demo app does not need mix however real apps likely will (optimize js/css) so install and then run that:
RUN npm install
RUN npx mix --production
```

... as it's in the repo now. And deployed. And it built and worked. Thinking about it, it _could_ be that the Laravel demo app does not need/use mix, and hence that flag does nothing and that's why it works. Hmm.

Are you deploying the demo app? And finding it _doesn't_ work for you? Which would ... be very odd. As it does for me.

Or do you mean that doesn't work when you swap in your app with _its_ mix stuff?

**Comment by gregmsanderson** [comment]
I wonder if it depends on the content of `webpack.mix.js` ... I'm thinking if your mix needs to do something different, or needs a plugin or something, that _may_ be what differs, and hence what's breaking.

Only the syntax of the npx flag is correct. I checked other npx examples.
